### PR TITLE
added cost estimation

### PR DESCRIPTION
**Pull request by broberts23**

### CODE REVIEW

**Comment by broberts23** [comment]
terrateam plan azure dev

**Comment by broberts23** [comment]
terrateam plan

**Comment by broberts23** [comment]
terrateam plan azure dev

**Comment by joshpollara** [comment]
This isn't valid yaml. The // lines are breaking the file.

**Comment by joshpollara** [comment]
Additionally, I'd suggest passing environment variables to checkov. Not args. I'll have to make a change to support extra args.

**Comment by broberts23** [comment]
@joshpollara 

/facepalm

the args are for my multi env tfvars though.
not for checkov?

workflows:
  - tag_query: azure dev
    plan:
      - type: init
      - type: plan
        extra_args: ["-var-file=dev.tfvars"]
      - type: run
        cmd: ['checkov-wrapper']
        capture_output: true

**Comment by broberts23** [comment]
terrateam plan azure dev

**Comment by broberts23** [comment]
terrateam plan

**Comment by joshpollara** [comment]
> @joshpollara 
> 
> /facepalm
> 
> the args are for my multi env tfvars though.
> not for checkov?
> 
> workflows:
>   - tag_query: azure dev
>     plan:
>       - type: init
>       - type: plan
>         extra_args: ["-var-file=dev.tfvars"]
>       - type: run
>         cmd: ['checkov-wrapper']
>         capture_output: true
> 

Ah cool! Misread on mobile.

**Comment by broberts23** [comment]
cost_estimation and checkov intergrated into terrateam config.yml

**Pull request merged**
