### PR TITLE
added dynamodb resource and vars

### PR DESCRIPTION
**Pull request by broberts23**

### CODE REVIEW

**Comment by broberts23** [comment]
terrateam feedback I don't understand why "Workspace: default" runs on plan?
I thought this was controlled by "create_and_select_workspace" (which i've set to false)

**Comment by joshpollara** [comment]
@broberts23 First of all, this is a failure of the documentation. I'm going to clean that up this weekend.

The issue is that your Terrateam configuration has the following `dirs` entry:
```yaml
dirs:
  azure:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
```

This configuration above only applies to the `azure` directory. It does *not* apply to directories under the `azure` directory. You have two options:

Option 1: Explicitly create configurations for each directory
```yaml
dirs:
  azure:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
  azure/foo:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
```

Option 2: Use a glob that applies to the `azure` directory and everything under it
```yaml
dirs:
  azure/**:
    create_and_select_workspace: false
    tags: [azure]
    workspaces:
      dev:
        tags: [dev]
```

**Comment by broberts23** [comment]
> @broberts23 First of all, this is a failure of the documentation. I'm going to clean that up this weekend.
> 
> The issue is that your Terrateam configuration has the following `dirs` entry:
> 
> ```
> Option 2: Use a glob that applies to the `azure` directory and everything under it
> 
> ```yaml
> dirs:
>   azure/**:
>     create_and_select_workspace: false
>     tags: [azure]
>     workspaces:
>       dev:
>         tags: [dev]
> ```

@joshpollara you're an absolute legend

now to work through the list of failures from checkov 🤣 (which is absolutely amazing btw)

**Comment by joshpollara** [comment]
@broberts23 I noticed you are attempting to set an environment variable in your custom workflow:
```yaml
      - type: env
        name: CKV_SKIP_CHECK
        cmd: ['LOW']
```

This should actually be:
```yaml
      - type: env
        name: CKV_SKIP_CHECK
        cmd: ['echo', 'LOW']
```

**Comment by broberts23** [comment]
> This should actually be:
> 
> ```yaml
>       - type: env
>         name: CKV_SKIP_CHECK
>         cmd: ['echo', 'LOW']
> ```
@joshpollara 
Noice. 


On a different note...
```yaml
dirs:
  azure/**:
```
what's sitting under azure/** is all the modules. terrateam is trying to process the modules individually,which is what was happening before, but in the defualt workspace
is there a way to ignore/exclude subdirectories?

**Comment by joshpollara** [comment]
@broberts23 this will ignore a dir:
```yaml
dirs:
  modules/foo:
    when_modified:
      file_patterns: []
```

**Comment by joshpollara** [comment]
> @broberts23 this will ignore a dir:
> 
> ```yaml
> dirs:
>   modules/foo:
>     when_modified:
>       file_patterns: []
> ```

Looks like your modules are under the azure directory so the entry under dirs would be `azure/modules/**`

Also, you can commit Terrateam configuration changes directly to your feature branch. Only access control is pulled from `main`.

**Comment by joshpollara** [comment]
Gotta sign off for the evening! I'll check tomorrow if you need anything.

**Comment by broberts23** [comment]
> > @broberts23 this will ignore a dir:
> > ```yaml
> > dirs:
> >   modules/foo:
> >     when_modified:
> >       file_patterns: []
> > ```
> 
> Looks like your modules are under the azure directory so the entry under dirs would be `azure/modules/**`
> 
> Also, you can commit Terraform configuration changes directly to your feature branch. Only access control is pulled from `main`.

you're too quick mate! i was just ingesting the docs 🤣 https://terrateam.io/docs/features/directories-and-globs

**Pull request merged**
